apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydep
  name: mydep
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mydep
  type: NodePort
status:
  loadBalancer: {}
